### ISSUE TITLE
Null pointer when deleting all captions from a playlist

### ISSUE THREAD

**Issue by angrave** [classtranscribe/WebAPI#124]
Null Pointer
 // Delete all captions. This caused a null pointer exception when
var captions = videos.SelectMany(v => v.Transcriptions).SelectMany(t => t.Captions).ToList();
 _context.Captions.RemoveRange(captions);

e.g. playlist b20296a4-3fb9-4cb5-905b-fb72f46f76af

**Comment by asherdale** [comment]
@angrave was this issue fixed by #127? Specifically looking at the null filters you added [here](https://github.com/classtranscribe/WebAPI/pull/127/files?file-filters%5B%5D=.cs&file-filters%5B%5D=.py&file-filters%5B%5D=.txt#diff-34cb1a3165623b84093347c1fef97ab6271e4de43e4b50fd7274b27143da0c44R372) and [here](https://github.com/classtranscribe/WebAPI/pull/127/files?file-filters%5B%5D=.cs&file-filters%5B%5D=.py&file-filters%5B%5D=.txt#diff-34cb1a3165623b84093347c1fef97ab6271e4de43e4b50fd7274b27143da0c44R379).
