### ISSUE TITLE
Don't report UNK as unknown university

### ISSUE THREAD

**Issue by angrave** [classtranscribe/WebAPI#13]
The university list should not report UNK as a listed, editable, university.
This could be filtered on the frontend but it's probably best to filter on the backend

**Comment by asherdale** [comment]
Do we want to filter out this university on the backend? From a brief look at "Seed.cs", the "UNK" university isn't referenced at all by any other seed data, so my initial instinct would be to just delete this Seed.cs file and then delete it from the prod DB. @angrave thoughts?

**Comment by angrave** [comment]
I believe it is used by the frontend before someone logs in (of if we cant determine what university they belong). Someone needs to grep the Frontend and backend code.

**Comment by asherdale** [comment]
Thanks for pointing that out to me, that's right. "UNK" university is used as a default option in both the frontend and the backend if we do not know a user's university.

How about this for a fix: on the GET request for all universities (`/api/Universities`), we filter out the "UNK" university. This would still keep the "UNK" university as an object in the database, and it could still be fetched with the GET request that takes a parameter (e.g. GET `/api/Universities/0000`).

@ruihuasui would this cause any potential errors in the frontend, or would this work? I am thinking that it would be fine because the `getUniversities()` function in `HomeController.js` already filters out the default university for the frontend, but just want to check with you.
