### ISSUE TITLE
Don't compress when serving static file content

### ISSUE THREAD

**Issue by angrave** [classtranscribe/WebAPI#201]
99.99% of static file content is already compressed (e.g. mp4, images), the static file server should not waste cpu time attempting to compress file content.

**Comment by asherdale** [comment]
Has this already been fixed by your implementation of the StaticFileController? Looking specifically at your change in line 205 in Startup.cs to stop using UseStaticFiles(): https://github.com/classtranscribe/WebAPI/pull/202/files#diff-94c73c9afc32e0bb113de06f7ac75732a090f9b7e2f621055f45e88119476482R205

The comment on lines 199-203 in Startup.cs mentions that you are explicitly turning off the compression, so should this issue be closed?
