### ISSUE TITLE
Request for new API: get watch time data joined by users and media

### ISSUE THREAD

**Issue by ruihuasui** [classtranscribe/WebAPI#50]
To get the data used for visualization, now frontend has to send multiple requests through the APIs for `logs`, and usually, it costs about 30 sec or more for some popular courses like CS241.

So maybe it's time to have special APIs for each data visualization `api/.../{offeringId}`. According to the issues [#150](https://github.com/classtranscribe/FrontEnd/issues/150) and [#131](https://github.com/classtranscribe/FrontEnd/issues/131) in `FrontEnd` (Especially for [#150](https://github.com/classtranscribe/FrontEnd/issues/150), we need to have a giant table joined by users and medias, and each cell in the table represents how much time a user spent on this media). 
Hence, we need an API that can return the following data:
- An array of users who have watched videos of this offering: each object should contain (1) the user's info, requiring their `id` and `email`; (2) an array of **ALL** the medias in this offering (not just the medias the user watched). should be ordered by their `indices`. 
- Each media object should have the count of `timeupdate` event type in `last1Hr`, `last3Days`, `lastWeek`, `lastMonth`, and `total` for this user. (if a media is not watched by the user, all the values should be 0)

```json
[
  {
    "user": {
      "id" : "",
      "email": ""
    },
    "medias": [
      {
        "mediaName": "",
        "id": "",
        "last1Hr": 12,
        "last3Days": 12,
        "lastWeek": 12,
        "lastMonth": 12,
        "total": 12
      }
    ]
  }
]
```

**Comment by asherdale** [comment]
Hey @ruihuasui, are you still looking for this to be made?

If so, I just want to confirm a couple of things. It seems like what you are looking for is very similar to the current `/api/Logs/CourseLogs` endpoint. The only differences between this existing endpoint and the new one that you want are:
- the existing endpoint doesn't include all of the medias in the offering for each user, it only includes medias that the user has actually watched
- the existing endpoint doesn't include the media name
- the existing endpoint doesn't include the "total" field

Would you like to me edit the existing endpoint to match your specifications, or should I create a completely new endpoint (something like `api/Logs/AllCourseLogs`)?

Also, just to clarify, is the "total" field supposed to be the total count of `timeupdate` logs for the given media ID since the beginning of time (no lower bound)?

**Comment by ruihuasui** [comment]
Hi @asherdale yes, these three differences are the intended features for this API. Also, I think it would be better to have a new endpoint to not break anything else.

**Comment by asherdale** [comment]
What should the authentication level be for this? Admins only, instructors + admin only, or students that can see the offering?

**Comment by ruihuasui** [comment]
Yes this endpoint should be accessible only for instructors and admins.
