### ISSUE TITLE
Initialize Video.JsonMetadata to an empty Jobject at creation

### ISSUE THREAD

**Issue by houyuan2** [classtranscribe/WebAPI#52]
When working on issue 34, I found that Video.JsonMetadata is initialized to null. It would be better to initialize it and all the other JObject fields defined under Model.cs to an empty JObject at the beginning. This would save the effort to explicitly check if JsonMetadata is null.

**Comment by asherdale** [comment]
Is this necessary? I think it is a best practice to check for null objects ("Defensive Programming") even if it is assumed that the objects are initialized

**Comment by angrave** [comment]
Not trusting data is the correct stance.

In the python code I did something like
result = 123 # Default
try { result = int(  new JsonObject( metadata).getProp('blah') ) } catch(exception ignored) {}
i.e. if the metadata is invalid or does not exist or the poperty is missing just ignore the exception run with the default value

FYI The C# ?? operator may or may not be useful 
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-coalescing-operator
List<int> numbers = null;
int? a = null;

(numbers ??= new List<int>()).Add(5);
Console.WriteLine(string.Join(" ", numbers));  // output: 5

numbers.Add(a ??= 0);
Console.WriteLine(string.Join(" ", numbers));  // output: 5 0
Console.WriteLine(a);  // output: 0

Re - database & entities
It is possible to declare that a database column (and entity field) is non-null. If we do this, please create a PR of only this migration, so we can revert it if necessary. We should also convert any existing null instances to a reasonable JSON string e.g. {} just prior to making the colummn NOT NULL

- i wonder if it is possible to do this as also part of the migration script or (gasp) directly using pgadmin 
e.g. something like
UPDATE  "Videos" SET JsonMetadata='{}' WHERE JsonMetadata IS NULL
 (I'm not a huge fan of running UPDATE on production data  but this seems fairly safe; it's been >10 years since I wrote a SQL UPDATE so the above maybe incorrect). FYI If we do this in pgadmin web interface we also need to include the schema for some reason.
UPDATE  public."Videos" SET JsonMetadata='{}' WHERE JsonMetadata IS NULL;

The most exciting thing about UPDATE statements is that if you forget the WHERE clause then it updates all rows. And there's no going back...

Anyway, that would ensure that we will never see or be able to insert nulls into the database again. We'd also want to ensure new objects are set to a non null "{}" before pushing this change, as a separate PR

**Comment by asherdale** [comment]
I'll work on this as @angrave suggested above. Specifically:
1. first, open a PR for making sure new Video entities always have non-null JObject properties (and add a unit test)
2. next, open a second PR for adding a `NOT NULL` constraint on the JObject columns of the `Videos` SQL table, and migrate existing values (this is easy to do in the migration script and is actually necessary to include in it, see [here](https://stackoverflow.com/questions/12462100/default-value-for-required-fields-in-entity-framework-migrations)).
3. Once the two PRs are merged, create a new issue and another pair of PRs that make the same change for all other JObject values
