### ISSUE TITLE
Server API should report a commit hash or build count number to indicate that frontend should clear the browser cache

### ISSUE THREAD

**Issue by ruihuasui** [classtranscribe/WebAPI#63]
Currently frontend are using latest commit's sha for the FrontEnd master branch to handle the browser cache.
> but there's a race condition with that because there's a window of time between master commit and when master is deployed. So some clients will see the new commit version while the old api is deployed; then wont know to clear the cache when the new version is deployed
> [view on teams](https://teams.microsoft.com/l/message/19:7d8179771abe4ff5a5f96705eacec52b@thread.tacv2/1597673193016?tenantId=44467e6f-462c-4ea2-823f-7800de5434e3&groupId=324b028e-f054-432e-a6b1-26ba7f217b81&parentMessageId=1597624914840&teamName=ClassTranscribeDev&channelName=devops&createdTime=1597673193016)

**Comment by angrave** [comment]
@ruihuasui 
Can we close this issue? The original suggestion was inaccurate - we want the frontend to check its own build number or hash.

Does the frontend now check to see if it is the correct build number or hash value of the frontend and download if it is not? Does it handle failure (e.g. because the server is unavailable) well?

**Comment by ruihuasui** [comment]
Yes, it checks the hash value in the config.js now.
